### ISSUE TITLE
mobile: break task (depends on #99)

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#107]
### User Story
**As a** mobile app user,  
**I want** a dedicated break screen feature within the app,  
**So that** I can enjoy a relaxing image or video and be aware of the time left during breaks, with the option to skip if needed.

### Acceptance Criteria
- [ ] Design a 'Take a Break' screen that displays a relaxing image or video.
- [ ] Include a countdown timer on the screen to show the time left for the break.
- [ ] Provide a 'Skip' button allowing users to end the break early if they choose.
- [ ] Ensure the break screen is easily accessible but unobtrusive to the user experience.
- [ ] The feature should be responsive and adapt to different device orientations and screen sizes.
- [ ] Validate that the feature does not consume excessive battery or data.

### Related Issues
- [Issue number]: Implementing user task flow for enhanced engagement.

### Notes
- The choice of images or videos should be curated to ensure they are universally perceived as relaxing.
- Consideration should be given to how the break feature might impact ongoing tasks within the app.

### Suggested Layout
![20240225_133336](https://github.com/uiowaSEP2024/001_DisAv/assets/56485548/034e00d9-352c-46c1-b0a0-4704c6db1208)

**Comment by bdesollar** [comment]
This is started on mobile

**Comment by bdesollar** [comment]
This is done on mobile
