### ISSUE TITLE
web: break task (depends on #100)

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#108]
### User Story
**As a** web app user,  
**I want** to have a 'Take a Break' feature within the web interface,  
**So that** I can enjoy a moment of relaxation with a calming image or video and be mindful of the break duration, with the flexibility to skip the break if desired.

### Acceptance Criteria
- [ ] Design and implement a 'Take a Break' screen that can display a relaxing image or video.
- [ ] Integrate a countdown timer that informs users of the remaining time for the break.
- [ ] Include a 'Skip' option for users who wish to bypass the break.
- [ ] The break screen should be non-intrusive and should not disrupt the overall user workflow.
- [ ] Ensure the feature is responsive and functions well across various browsers and screen sizes.
- [ ] The media used should be optimized for web to prevent long loading times and excessive bandwidth usage.

### Related Issues
- [Issue number]: Enhance user engagement and experience on the web platform.

### Notes
- The media for the break screen should be chosen to cater to a diverse audience and create a universally relaxing atmosphere.
- The impact of the break feature on any background tasks or processes within the web app should be considered and handled appropriately.

### Suggested Layout
![20240225_133355](https://github.com/uiowaSEP2024/001_DisAv/assets/56485548/a26ab031-4a42-48c0-bdbf-c631805422de)

**Comment by aezouhri** [comment]
Starting this up on web side.

**Comment by aezouhri** [comment]
Completed on web side. PR is being opened.
