### ISSUE TITLE
Bug: Can't log back into mobile after logout

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#128]
**Describe the bug**
After creating an account and logging in to the mobile app, when I sign out and try to log back in i get a user not found error message
**To Reproduce**

1. Go to Mobile app
2. Create a user
3. Log out with that user
4. Attempt to log back in
5. See error

**Expected behavior**
I Should be able to log back in normally

**Screenshots**
If applicable, add s
![ezgif com-resize](https://github.com/uiowaSEP2024/001_DisAv/assets/56485548/b3a79e25-7c6f-41e4-8423-1f8cfc26b874)
creenshots to help explain your problem.

**Comment by saanbe16** [comment]
@bdesollar Can you look into how you are logging users out? Let me know if this works on your end

**Comment by bdesollar** [comment]
This is done
