### ISSUE TITLE
Test: mobile reading task screen

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#150]
#### Reading Tasks Screen Testing on Mobile
1. **Navigation Testing:**
    - Verify that the reading tasks screen is accessible from the mobile application's navigation menu.
    - Ensure that users can navigate back to the main screens from the reading tasks screen.
2. **Display Testing:**
    - Test the reading tasks screen on various mobile devices and screen sizes to verify accurate display of reading tasks.
    - Ensure that the list of books is properly formatted and displayed within the screen boundaries.
3. **Functionality Testing:**
    - Test the functionality to add new books to the reading list.
    - Verify that new books added by the user are correctly reflected in the reading tasks screen and database.
4. **Usability Testing:**
    - Evaluate the responsiveness and usability of the reading tasks screen across different mobile platforms (iOS, Android).
    - Ensure that users can easily interact with the reading tasks screen elements and perform tasks without difficulty.
5. **Error Handling Testing:**
    - Test error scenarios such as adding duplicate books or invalid inputs to ensure proper error handling.
    - Verify that appropriate error messages are displayed to the user when encountering errors.
6. **Documentation Testing:**
    - Review the documentation to ensure that all changes made to the codebase are properly documented for future reference.

**Comment by bdesollar** [comment]
Starting this on mobile
