### ISSUE TITLE
Test: mobile view book summaries

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#159]
#### Test Scenarios
1. **Valid Book Selection**
    - **Description:** Clicking on a book to view its summary.
    - **Steps:**
        1. Navigate to the book list on the web application.
        2. Click on a specific book to view its summary.
    - **Expected Result:** The detailed summary of the selected book is displayed on the screen.

2. **Book Details Display**
    - **Description:** Verify that relevant book details are displayed on the summary screen.
    - **Steps:**
        1. Navigate to the book summary screen for a selected book.
        2. Verify that the book's title, author, genre, and other relevant details are correctly displayed.
    - **Expected Result:** All relevant book details are accurately displayed on the summary screen.

3. **Button for Creating New Summaries**
    - **Description:** Checking the presence and functionality of the button to create new summaries.
    - **Steps:**
        1. Navigate to the book summary screen for a selected book.
        2. Look for a button or option to create new summaries for the book.
        3. Click on the button or option.
    - **Expected Result:** A button or option to create new summaries for the selected book is present and functional.

4. **Database Integration**
    - **Description:** Verify that book summaries are fetched from the database, if available.
    - **Steps:**
        1. Navigate to the book summary screen for a selected book.
        2. Verify that the summary displayed matches the information stored in the database.
    - **Expected Result:** Book summaries are fetched accurately from the database and displayed on the summary screen.

5. **Responsiveness**
    - **Description:** Test the functionality on different devices and screen sizes.
    - **Steps:**
        1. Access the book summary screen from various devices (e.g., desktop, tablet, mobile).
        2. Verify that the interface is responsive and functional on each device.
    - **Expected Result:** The functionality to view book summaries works smoothly across different devices and screen sizes.

6. **Error Handling**
    - **Description:** Verify proper error handling for unexpected scenarios.
    - **Steps:**
        1. Introduce errors such as server downtime or network issues during book summary retrieval.
        2. Attempt to view book summaries under these conditions.
    - **Expected Result:** The system gracefully handles errors and provides appropriate error messages or fallback mechanisms.

#### Notes
- Execute the test scenarios sequentially, ensuring thorough coverage of all functionalities.
- Record and report any issues encountered during testing for further investigation and resolution.
- Collaborate with developers to address any identified issues and ensure the stability and reliability of the book summary feature.

**Comment by bdesollar** [comment]
Starting this on mobile

**Comment by saanbe16** [comment]
Irrelavent now
