### ISSUE TITLE
Mobile: Tasks screen

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#99]
### User Story
**As a** mobile user,  
**I want** a tasks screen where I can view and complete my current tasks,  
**So that** I can easily track my progress and stay organized with my activities.

### Acceptance Criteria
- [ ] Design and implement a basic tasks screen in the mobile app.
- [ ] In the future this screen will display all different types of tasks
### Related Issues
- None

**Comment by bdesollar** [comment]
Started on this @saanbe16

**Comment by bdesollar** [comment]
This is done
